### ISSUE TITLE
Homepage: 404 error

### ISSUE THREAD

**Issue by ndaidong** [groovel/cmsgroovel#1]
Hi guys,

After downloading source code and .sql file, I extracted them, created database, imported schema, and then started following the guideline from readme.

Here is the first problem I faced:

![Error](http://i.imgur.com/c0mQCQ1.png)

The reason is it could not connect to database. Updating /config/database.php with correct connection info solved the problem.

Then I configured nginx and virtual domain to access website. But I got a "server error'. Here is log:

```
2016/01/21 14:23:12 [error] 2768#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/v$
Stack trace:
#0 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 /var/www/temp/groovecms/cms/groovel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(49): Monolog\Logger->error(Object(UnexpectedValueException))
#4 /var/www/temp/groov...
PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/temp/groovecms/cms/groovel/storage/logs/laravel.log" coul$
Stack trace:
#0 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorExce$
#3 /var/www/temp/groovecms/cms/groovel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handl
2016/01/21 14:23:14 [error] 2768#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/v$
Stack trace:
#0 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 /var/www/temp/groovecms/cms/groovel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(49): Monolog\Logger->error(Object(UnexpectedValueException))
#4 /var/www/temp/groov...
PHP message: PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/temp/groovecms/cms/groovel/storage/logs/laravel.log" coul$
Stack trace:
#0 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/temp/groovecms/cms/groovel/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorExce$
#3 /var/www/temp/groovecms/cms/groovel/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handl
```

I guessed the error related to permission. Right, changing "storage" mod to 0777 solved problem. And now the result I'm seeing:

![404 error](http://i.imgur.com/QMp9Kvg.png)

Where was I wrong? I have no idea to fix it. What I should do now?

Thanks.
Dong

**Comment by groovel** [comment]
Hello i see your uri, 
You need to write in your navigator web http://xxx/admin , admin is to go to the backendconsole , by default when you just write the root ,you access to the front end your apps but you don t have unless you deploy it in choose template in the back-end console

**Comment by ndaidong** [comment]
Thanks. Got it. Then which account I can use to login now?

**Comment by groovel** [comment]
Default is groovel/groovel 
Yours
